version: "3"

services:
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    restart: always

  nginx:
    depends_on:
      - web-service
    image: nginx:1.24.0
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/html:/usr/share/nginx/html
    restart: always
    ports:
        - '8000:80'
    build: nginx/