version: "3"

services:
    web-service:
        depends_on:
            - mongodb
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - ${WEB_SERVER_PORT}
        restart: always

    mongodb:
        image: mongodb/mongodb-community-server:6.0-ubi8
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - ${DB_PORT}

    nginx:
        depends_on:
            - web-service
        image: nginx:1.24.0
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/html:/usr/share/nginx/html
        restart: always
        ports:
            - ${NGINX_PORT}
        build: nginx/
