version: "3"

services:

  db-auth:
    image: redis:latest
    ports:
      - '6379:6379'

  app-auth:
    depends_on:
      - db-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    links:
      - db-auth

#volumes:
#  db:
#    driver: local